#!/usr/bin/env python3
# =============================================================================
# scripts/gen-compat-matrix.py
# -----------------------------------------------------------------------------
# Generates docs/compatibility/matrix.md (D-165) from the target tables below.
# Build-pipeline tooling (D-148; D-169). The prose is authored here; the three
# status tables — Tier-1 automated, editions, Tier-2 attestation — are the
# parts that change as CI verifies a version or an attestation lands, so they
# are data. A maintainer edits the TIER1 / EDITIONS / TIER2 lists (or a future
# revision wires them to CI results + parsed attestation issues) and re-runs
# this script; CI's `--check` fails if matrix.md drifts from the generator.
#
# Per D-148 this never runs on a user's SQL Server.
#
# Usage:  python scripts/gen-compat-matrix.py            # write the page
#         python scripts/gen-compat-matrix.py --check    # fail if out of date
# =============================================================================
from __future__ import annotations
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "docs" / "compatibility" / "matrix.md"

# Releases whose full six-target Docker matrix passed FAIL=0 (updated per tag).
VALIDATED_THROUGH = "v0.4.1 / v0.4.2 / v0.4.3"

# Tier 1 — automated CI on Linux containers (D-120), blocking.
TIER1 = [
    ("SQL Server 2017", "Linux", "✅ Verified (Tier 1)"),
    ("SQL Server 2019", "Linux", "✅ Verified (Tier 1)"),
    ("SQL Server 2022", "Linux", "✅ Verified (Tier 1)"),
    ("SQL Server 2025", "Linux", "✅ Verified (Tier 1)"),
]

# Editions and their EngineEdition value (SERVERPROPERTY('EngineEdition')).
EDITIONS = [
    ("Developer", "3", "✅ Verified", "Full feature set; `PAGE` compression."),
    ("Standard", "2", "✅ Verified", "`PAGE` compression on 2016+."),
    ("Express", "4", "✅ Verified",
     "No compression (cascades off, D-034); no SQL Agent — job creation skipped with a status row (D-116)."),
    ("Enterprise", "3", "⚙ Same engine as Developer",
     "Engine behavior identical to Developer (EngineEdition 3); not separately containerized."),
]

# Tier 2 — manual attestation (D-121/D-164); Unverified until attested.
TIER2 = [
    ("SQL Server 2012 (Windows)", "⏳ Pending attestation"),
    ("SQL Server 2014 (Windows)", "⏳ Pending attestation"),
    ("SQL Server 2016 (Windows)", "⏳ Pending attestation"),
    ("Azure SQL Managed Instance", "⏳ Pending attestation"),
    ("Azure SQL Database",
     "⏳ Pending attestation (heavy degradation expected: per-DB install, no Agent/msdb/error log — D-109)"),
]


def table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for r in rows:
        out.append("| " + " | ".join(r) + " |")
    return "\n".join(out)


def page():
    return f"""# Compatibility matrix

Supported engine range: **SQL Server 2012 through 2025**, on-prem and cloud, with
capability-driven degradation (D-108). Synapse, Fabric, Big Data Clusters, and
Stretch are out of scope.

> **Verification tiers.** **Tier 1** = automated CI on Linux containers, blocking
> (D-120). **Tier 2** = manual attestation for targets that cannot be
> containerized for free, not merge-blocking (D-121/D-164). **Tier 3** =
> community reports (non-binding, D-166). A target's status is only as strong as
> the tier that verified it.

## Tier 1 — automated (verified green)
Validated on every release through {VALIDATED_THROUGH} (six-target Docker
matrix, FAIL=0) and enforced per-push by `ci-tier1`:

{table(["Version", "Platform", "Status"], TIER1)}

## Editions (verified)
{table(["Edition", "EngineEdition", "Status", "Notes"], EDITIONS)}

## Tier 2 — manual attestation (pending)
These cannot be containerized in CI; status comes from community attestations
filed via the **version-compat** issue template (D-164). Until an attestation
arrives, status is **Unverified** — it is not a claim of breakage, only of
untested.

{table(["Target", "Status"], TIER2)}

**v1.0 gate:** at least **4 of 5** Tier-2 targets attested (§11.6). The staleness
policy (D-164) moves a target to *Unverified* after 3 minors without an
attestation and opens a deprecation discussion after 6; the process is on an
18-month post-1.0 review (D-190).

## How to contribute an attestation
Open a **Version compatibility / Tier-2 attestation** issue with your Install →
Collect → Report → Uninstall results and the capability snapshot. See
[.github/ISSUE_TEMPLATE/version-compat.yml](../../.github/ISSUE_TEMPLATE/version-compat.yml).

---
*Generated by `scripts/gen-compat-matrix.py` (D-165/D-169) — edit the target
tables in that script (or let CI regenerate) rather than this file. The
doc-coverage job runs `--check` and fails if this page drifts from the generator.*
"""


def main():
    check = "--check" in sys.argv
    new = page()
    if check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != new:
            print("STALE compatibility matrix (run scripts/gen-compat-matrix.py).")
            return 1
        print("compatibility matrix up to date.")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(new, encoding="utf-8", newline="\n")
    print(f"generated {OUT.relative_to(OUT.parents[2])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
